using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Midify.enums
{
    public enum MidiController
    {
        BankSelect = 0,
        ModulationWheel = 1,
        BreathController = 2,
        FootPedal = 4,
        PortamentoTime = 5,
        DataEntry = 6,
        Volume = 7,
        Balance = 8,
        Pan = 10,
        Expression = 11,
        EffectController1 = 12,
        EffectController2 = 13,
        GeneralPurpose1 = 16,
        GeneralPurpose2 = 17,
        GeneralPurpose3 = 18,
        GeneralPurpose4 = 19,
        BankSelectLSB = 32,
        ModulationWheelLSB = 33,
        BreathControllerLSB = 34,
        FootPedalLSB = 36,
        PortamentoTimeLSB = 37,
        DataEntryLSB = 38,
        VolumeLSB = 39,
        BalanceLSB = 40,
        PanLSB = 42,
        ExpressionLSB = 43,
        EffectController1LSB = 44,
        EffectController2LSB = 45,
        GeneralPurpose1LSB = 48,
        GeneralPurpose2LSB = 49,
        GeneralPurpose3LSB = 50,
        GeneralPurpose4LSB = 51,
        DamperPedal = 64,
        Portamento = 65,
        SostenutoPedal = 66,
        SoftPedal = 67,
        LegatoFootswitch = 68,
        Hold2 = 69,
        SoundController1 = 70,
        SoundController2 = 71,
        SoundController3 = 72,
        SoundController4 = 73,
        SoundController5 = 74,
        SoundController6 = 75,
        SoundController7 = 76,
        SoundController8 = 77,
        SoundController9 = 78,
        SoundController10 = 79,
        GeneralPurposeDecay = 80,
        GeneralPurposeHiPass = 81,
        GeneralPurpose5 = 82,
        GeneralPurpose6 = 83,
        HiResVelocity = 88,
        Effect1Depth = 91,
        Effect2Depth = 92,
        Effect3Depth = 93,
        Effect4Depth = 94,
        Effect5Depth = 95,
        DataIncrement = 96,
        DataDecrement = 97,
        NonRegisteredParamNumberLSB = 98,
        NonRegisteredParamNumberMSB = 99,
        RegisteredParamNumberLSB = 100,
        RegisteredParamNumberMSB = 101
    }
}
